name: arm64
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: toolchain
      run: sudo apt update && sudo apt install -qy g++-aarch64-linux-gnu
    # build project
    - name: build
      run: make cross
