name: arm64
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: toolchain
      run: sudo apt update && sudo apt install -qy g++-aarch64-linux-gnu
    # build project
    - name: build
      run: aarch64-linux-gnu-g++ web_server.cpp -pthread -lboost_filesystem -lboost_thread -lboost_system -std=c++17 -mcpu=cortex-a35 -O3 -o server_arm.bin
